### ISSUE TITLE
JSON deserialization error

### ISSUE THREAD

**Issue by joshgel** [tql-inc/DbtHelper#1]
Trying to run:
`DbtHelper --working-directory <<full_path>>/dw_all --gen-specific mcl --dry-run`

```
manifest.json deserialization failed
Initialization failed. Aborting
FSharp.Json.JsonDeserializationError: JSON Path: nodes.seed.dw_all.mcl_payment_rates.depends_on. Non option field is missing
   at Program.main(String[] argv) in /Users/josh/Code/src/playground/dbt-documentor/Program.fs:line 434
```

The dbt project itself runs with no issues. Any suggestions?

**Comment by ahaym** [comment]
Will take a look tomorrow, thanks for the report. Have had a lot of problems with projects that have seeds, hopefully I can fix that quickly

通过 Proton Mail 移动端发送

--------原始邮件--------
2023年4月22日 下午5:28，joshgel 来信：

**Comment by ahaym** [comment]
d30e681 should fix this. I tested it with a seed .csv file, let me know if the error persists
